version: '3'
services:
  jupyterhub:
    image: docker.io/jupyterhub/jupyterhub:3
    ports:
      - 8000:8000
    volumes:
      - jupyterhub_data:/srv/jupyterhub
volumes:
  jupyterhub_data:
    driver: local
    size: 0.5Gi
